
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author tmeyer
 */
import java.awt.datatransfer.*;
import java.awt.Toolkit;

public class TIN extends javax.swing.JFrame {

    /*
     Copies given value to the clipboard   
     @param str
     */
    public void copyToClipboard(String str) {
        StringSelection strSel = new StringSelection(str);
        Clipboard clpboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpboard.setContents(strSel, strSel);
    }

    /**
     * Creates new form TIN
     *
     * @param zahl
     * @return
     */
    public static int pruefsumme(long zahl) {
        long qs = 0;
        while (zahl != 0) {
            qs = qs + zahl % 10;
            zahl = zahl / 10;
        }
        qs = qs % 10;
        return (int) qs;

    }

    public TIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        edausgabe = new javax.swing.JTextField();
        bttin = new javax.swing.JButton();
        edbetriebsnummer = new javax.swing.JTextField();
        btbetriebsnummer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btclose = new javax.swing.JButton();
        btClipboardBetrNr = new javax.swing.JButton();
        btClipboardTIN = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        edausgabe.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edausgabe.setText("TIN-Nummer");
        edausgabe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edausgabeActionPerformed(evt);
            }
        });

        bttin.setText("TIN");
        bttin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttinMouseClicked(evt);
            }
        });
        bttin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttinActionPerformed(evt);
            }
        });

        edbetriebsnummer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edbetriebsnummer.setText("Betriebsnummer");

        btbetriebsnummer.setText("BetrNr");
        btbetriebsnummer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btbetriebsnummerMouseClicked(evt);
            }
        });
        btbetriebsnummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbetriebsnummerActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BetrNr Generator");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TIN-Generator");

        btclose.setText("Schließen");
        btclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcloseActionPerformed(evt);
            }
        });

        btClipboardBetrNr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_clipboard.png"))); // NOI18N
        btClipboardBetrNr.setToolTipText("copy to clipboard");
        btClipboardBetrNr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btClipboardBetrNrMouseClicked(evt);
            }
        });

        btClipboardTIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_clipboard.png"))); // NOI18N
        btClipboardTIN.setToolTipText("copy to clipboard");
        btClipboardTIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btClipboardTINMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btclose, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(edausgabe, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bttin, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btClipboardTIN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btbetriebsnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edbetriebsnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btClipboardBetrNr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edbetriebsnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btbetriebsnummer))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edausgabe, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bttin))
                            .addComponent(btClipboardTIN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btclose, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btClipboardBetrNr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btClipboardBetrNr.getAccessibleContext().setAccessibleName("bt_clipboard_betrNr");
        btClipboardTIN.getAccessibleContext().setAccessibleName("bt_clipboard_tin");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttinMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_bttinMouseClicked
    {//GEN-HEADEREND:event_bttinMouseClicked
        int[] zahlen
                = {
                    0, 1, 2, 3, 4, 5, 6, 7, 8, 9
                };
        int i;
        int summe;
        int produkt = 10;
        String ausgabe;
        StringBuilder sb = new StringBuilder(zahlen.length);

        zahlen = Array_mischen.arrayMix(zahlen);
        if (Math.random() * 2 > 1) {
            zahlen[1] = zahlen[2];/*Überscheiben da eine Zahl doppelt und eine nicht 
             * vorhanden sein soll*/

        } else {
            //Es sind jetzt auch drei gleiche Zahlen möglich.
            zahlen[1] = zahlen[0];
            zahlen[2] = zahlen[0];
        }

        zahlen = Array_mischen.arrayMix(zahlen);

        //Berechnen der Prüfziffer
        for (i = 0; i < 10; i++) {
            summe = (zahlen[i] + produkt) % 10;
            if (summe == 0) {
                summe = 10;
            }
            produkt = (summe * 2) % 11;
        }
        int prüfziffer = 11 - produkt;
        if (prüfziffer == 10) {
            prüfziffer = 0;
        }
        for (int j : zahlen) {
            sb.append(j);
        }
        ausgabe = sb.toString();
        edausgabe.setText(ausgabe + "" + prüfziffer);
    }//GEN-LAST:event_bttinMouseClicked

    private void edausgabeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_edausgabeActionPerformed
    {//GEN-HEADEREND:event_edausgabeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edausgabeActionPerformed

    private void bttinActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bttinActionPerformed
    {//GEN-HEADEREND:event_bttinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttinActionPerformed

    private void btbetriebsnummerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btbetriebsnummerActionPerformed
    {//GEN-HEADEREND:event_btbetriebsnummerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btbetriebsnummerActionPerformed

    private void btbetriebsnummerMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btbetriebsnummerMouseClicked
    {//GEN-HEADEREND:event_btbetriebsnummerMouseClicked
        /* Erstellen einer Betriebsnummer, also eine achtstellige
         * Zufallszahl. Die achte Stelle ist eine Prüfsumme, für diese
         * wird zunächst die Quersumme aus den sieben Zufallszahlen gebildet.
         * Restwert aus Mod10 ergibt dann die Prüfsumme.*/
        int[] betrzahlen = new int[8];
        int[] betrzahlenqs = new int[7];
        StringBuilder sb2 = new StringBuilder();
        StringBuilder sb3 = new StringBuilder();
        int maxLength = 10; //Länge für den Long der Quersummenberechnung. Der umgewandelte String sollte nicht länger als 10 werden.
        String ausgabebetriebsnummer;
        String betrnrquersumme;
        long betrnrquersummeLong;
        int i;
        //Bilden der Zufallszahlen von 0-9
        for (i = 0; i < betrzahlen.length - 1; i++) {
            betrzahlen[i] = (int) (Math.random() * 9);
        }
        if ((betrzahlen[0] == 1 && betrzahlen[1] == 0) || (betrzahlen[0] == 0 && betrzahlen[1] == 0)) {
            betrzahlen[1] = 1;
        }
        if (betrzahlen[1] == 1 && betrzahlen[2] == 0) {
            betrzahlen[2] = 1;
        }
        //Verrechnen der Zahlen mit der Vorgegebenen Wichtung in separates Array
        betrzahlenqs[0] = betrzahlen[0];
        betrzahlenqs[1] = betrzahlen[1] * 2;
        betrzahlenqs[2] = betrzahlen[2];
        betrzahlenqs[3] = betrzahlen[3] * 2;
        betrzahlenqs[4] = betrzahlen[4];
        betrzahlenqs[5] = betrzahlen[5] * 2;
        betrzahlenqs[6] = betrzahlen[6];

        //Bilden einer Stringzahl
        for (int x : betrzahlenqs) {
            sb3.append(x);
        }
        betrnrquersumme = sb3.toString();

        betrnrquersummeLong = Long.parseLong(betrnrquersumme, maxLength); //Der String

        //Setzen der Prüfsumme für die achte Stelle durch die Funktion "quersumme"
        betrzahlen[7] = pruefsumme(betrnrquersummeLong);
        //Bilden eines Strings aus den Werten des Arrays für die Ausgabe
        for (int y : betrzahlen) {
            sb2.append(y);
        }

        ausgabebetriebsnummer = sb2.toString();
        edbetriebsnummer.setText(ausgabebetriebsnummer);

    }//GEN-LAST:event_btbetriebsnummerMouseClicked

    private void btcloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btcloseActionPerformed
    {//GEN-HEADEREND:event_btcloseActionPerformed
        dispose();
    }//GEN-LAST:event_btcloseActionPerformed

    private void btClipboardBetrNrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btClipboardBetrNrMouseClicked
        String str = edbetriebsnummer.getText();
        copyToClipboard(str);
    }//GEN-LAST:event_btClipboardBetrNrMouseClicked

    private void btClipboardTINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btClipboardTINMouseClicked
        String str = edausgabe.getText();
        copyToClipboard(str);
    }//GEN-LAST:event_btClipboardTINMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Metal look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TIN().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClipboardBetrNr;
    private javax.swing.JButton btClipboardTIN;
    private javax.swing.JButton btbetriebsnummer;
    private javax.swing.JButton btclose;
    private javax.swing.JButton bttin;
    private javax.swing.JTextField edausgabe;
    private javax.swing.JTextField edbetriebsnummer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
